const print = (text) => {
  console.log('🚀 ~ ', text);
};

const generateGuid = () => {
  var result, i, j;
  result = '';
  for (j = 0; j < 32; j++) {
    if (j == 8 || j == 12 || j == 16 || j == 20) result = result + '-';
    i = Math.floor(Math.random() * 16)
      .toString(16)
      .toUpperCase();
    result = result + i;
  }
  return result;
};

const sleep = (ms) => new Promise((res) => setTimeout(res, ms * 1000));

const DEFAULT_COLLAGE_TEMPLATE = {
  'objects': [
    {
      'angle': 0,
      'backgroundColor': '',
      'fill': 'rgb(0,0,0)',
      'fillRule': 'nonzero',
      'flipX': false,
      'flipY': false,
      'globalCompositeOperation': 'source-over',
      'height': 202,
      'id': 'images-1',
      'interactive': false,
      'layoutManager': {
        'strategy': 'fit-content',
        'type': 'layoutManager'
      },
      'left': 8.7282,
      'objects': [
        {
          'angle': 0,
          'backgroundColor': '',
          'fill': 'transparent',
          'fillRule': 'nonzero',
          'flipX': false,
          'flipY': false,
          'globalCompositeOperation': 'source-over',
          'height': 200,
          'id': null,
          'left': -101,
          'opacity': 1,
          'originX': 'left',
          'originY': 'top',
          'paintFirst': 'fill',
          'rx': 0,
          'ry': 0,
          'scaleX': 1,
          'scaleY': 1,
          'shadow': null,
          'skewX': 0,
          'skewY': 0,
          'stroke': 'black',
          'strokeDashArray': null,
          'strokeDashOffset': 0,
          'strokeLineCap': 'butt',
          'strokeLineJoin': 'miter',
          'strokeMiterLimit': 4,
          'strokeUniform': false,
          'strokeWidth': 2,
          'top': -101,
          'type': 'Rect',
          'version': '6.4.2',
          'visible': true,
          'width': 200
        },
        {
          'angle': 0,
          'backgroundColor': '',
          'charSpacing': 0,
          'direction': 'ltr',
          'fill': 'rgb(0,0,0)',
          'fillRule': 'nonzero',
          'flipX': false,
          'flipY': false,
          'fontFamily': 'Calibri',
          'fontSize': 20,
          'fontStyle': 'normal',
          'fontWeight': 'normal',
          'globalCompositeOperation': 'source-over',
          'height': 22.6,
          'id': null,
          'left': -1,
          'lineHeight': 1.16,
          'linethrough': false,
          'opacity': 1,
          'originX': 'center',
          'originY': 'center',
          'overline': false,
          'paintFirst': 'fill',
          'pathAlign': 'baseline',
          'pathSide': 'left',
          'pathStartOffset': 0,
          'scaleX': 1,
          'scaleY': 1,
          'shadow': null,
          'skewX': 0,
          'skewY': 0,
          'stroke': null,
          'strokeDashArray': null,
          'strokeDashOffset': 0,
          'strokeLineCap': 'butt',
          'strokeLineJoin': 'miter',
          'strokeMiterLimit': 4,
          'strokeUniform': false,
          'strokeWidth': 1,
          'styles': [],
          'text': '1',
          'textAlign': 'center',
          'textBackgroundColor': '',
          'top': -1,
          'type': 'Text',
          'underline': false,
          'version': '6.4.2',
          'visible': true,
          'width': 10
        }
      ],
      'opacity': 1,
      'originX': 'left',
      'originY': 'top',
      'paintFirst': 'fill',
      'scaleX': 3.047,
      'scaleY': 3.047,
      'shadow': null,
      'skewX': 0,
      'skewY': 0,
      'stroke': null,
      'strokeDashArray': null,
      'strokeDashOffset': 0,
      'strokeLineCap': 'butt',
      'strokeLineJoin': 'miter',
      'strokeMiterLimit': 4,
      'strokeUniform': false,
      'strokeWidth': 0,
      'subTargetCheck': false,
      'top': 11.1621,
      'type': 'Group',
      'version': '6.4.2',
      'visible': true,
      'width': 202
    },
    {
      'angle': 0,
      'backgroundColor': '',
      'fill': 'rgb(0,0,0)',
      'fillRule': 'nonzero',
      'flipX': false,
      'flipY': false,
      'globalCompositeOperation': 'source-over',
      'height': 202,
      'id': 'images-2',
      'interactive': false,
      'layoutManager': {
        'strategy': 'fit-content',
        'type': 'layoutManager'
      },
      'left': 532.6683,
      'objects': [
        {
          'angle': 0,
          'backgroundColor': '',
          'fill': 'transparent',
          'fillRule': 'nonzero',
          'flipX': false,
          'flipY': false,
          'globalCompositeOperation': 'source-over',
          'height': 200,
          'id': null,
          'left': -101,
          'opacity': 1,
          'originX': 'left',
          'originY': 'top',
          'paintFirst': 'fill',
          'rx': 0,
          'ry': 0,
          'scaleX': 1,
          'scaleY': 1,
          'shadow': null,
          'skewX': 0,
          'skewY': 0,
          'stroke': 'black',
          'strokeDashArray': null,
          'strokeDashOffset': 0,
          'strokeLineCap': 'butt',
          'strokeLineJoin': 'miter',
          'strokeMiterLimit': 4,
          'strokeUniform': false,
          'strokeWidth': 2,
          'top': -101,
          'type': 'Rect',
          'version': '6.4.2',
          'visible': true,
          'width': 200
        },
        {
          'angle': 0,
          'backgroundColor': '',
          'charSpacing': 0,
          'direction': 'ltr',
          'fill': 'rgb(0,0,0)',
          'fillRule': 'nonzero',
          'flipX': false,
          'flipY': false,
          'fontFamily': 'Calibri',
          'fontSize': 20,
          'fontStyle': 'normal',
          'fontWeight': 'normal',
          'globalCompositeOperation': 'source-over',
          'height': 22.6,
          'id': null,
          'left': -1,
          'lineHeight': 1.16,
          'linethrough': false,
          'opacity': 1,
          'originX': 'center',
          'originY': 'center',
          'overline': false,
          'paintFirst': 'fill',
          'pathAlign': 'baseline',
          'pathSide': 'left',
          'pathStartOffset': 0,
          'scaleX': 1,
          'scaleY': 1,
          'shadow': null,
          'skewX': 0,
          'skewY': 0,
          'stroke': null,
          'strokeDashArray': null,
          'strokeDashOffset': 0,
          'strokeLineCap': 'butt',
          'strokeLineJoin': 'miter',
          'strokeMiterLimit': 4,
          'strokeUniform': false,
          'strokeWidth': 1,
          'styles': [],
          'text': '2',
          'textAlign': 'center',
          'textBackgroundColor': '',
          'top': -1,
          'type': 'Text',
          'underline': false,
          'version': '6.4.2',
          'visible': true,
          'width': 10
        }
      ],
      'opacity': 1,
      'originX': 'left',
      'originY': 'top',
      'paintFirst': 'fill',
      'scaleX': 1.2654,
      'scaleY': 0.7142,
      'shadow': null,
      'skewX': 0,
      'skewY': 0,
      'stroke': null,
      'strokeDashArray': null,
      'strokeDashOffset': 0,
      'strokeLineCap': 'butt',
      'strokeLineJoin': 'miter',
      'strokeMiterLimit': 4,
      'strokeUniform': false,
      'strokeWidth': 0,
      'subTargetCheck': false,
      'top': 646.384,
      'type': 'Group',
      'version': '6.4.2',
      'visible': true,
      'width': 202
    }
  ],
  'version': '6.4.2'
};

const VERO_BRANDS = [
  'salt gun',
  'bestway',
  'advanced nutrients',
  'jobe’s organics',
  'golf',
  'golf set',
  'golf iron set',
  'recover tactical',
  'stngr usa',
  'stngrusa',
  'roundfire',
  'ck',
  'pic',
  'elegant disposables',
  'funboy',
  'kona',
  'magnets',
  'uocasi',
  'teexpert',
  'pour homme',
  'eau de toilette',
  'tesla',
  'zzem screw',
  'd&l company, llc - stomprocket',
  'whaiffa',
  'audio-technica',
  'stomp rocket',
  'czs',
  'nat leathers',
  'pearce grip',
  'silverado',
  'cheverolet',
  'es engineered by schildmeier',
  'woof pet inc',
  'tiki',
  'meta',
  'soundpeats',
  'golf wedge set',
  'wdgg',
  'airmoto',
  'jyoko',
  'poolrx',
  'junninggor',
  'waterdrop',
  'stud 100',
  'skeeter',
  'safer',
  'trifecta',
  'lysol',
  'couples card game',
  'pty limited',
  'welmate',
  'mywoof',
  'woof pet',
  'anacis',
  'kitsch',
  'plan b',
  'protein',
  'parfum',
  'deodorant',
  'freshener',
  'gallant metals',
  'solution',
  'facial',
  'probiotics',
  'booster',
  'glucose',
  'argan',
  'metabolic',
  'castor',
  'urine',
  'thyroid',
  'perfume',
  'ozium',
  'clinical results 24/7',
  'catheter',
  'hypoallergenic',
  'hyaluronic',
  'enzymes',
  'bergamot',
  'collagen',
  'wrinkle',
  'hygrometer',
  'hobo',
  'vitamin',
  'caplets',
  'magnesium',
  'probiotic',
  'hyperhidrosis',
  'omega-3',
  'smoking',
  'nicotine',
  'odoban',
  'neoprene',
  'ointement',
  'detergent',
  'goodal',
  'sukin',
  'queen',
  'audi',
  'dodge',
  'retinol',
  'acne',
  'hemorrhoid',
  'herbal',
  'rust',
  'aerosol',
  'honda',
  'extinguisher',
  'scent',
  'stain',
  'antiaging',
  'purse',
  'tote',
  'gummies',
  'acetaminophen',
  'acid',
  'spy',
  'cleaner',
  'eyeliner',
  'kajal',
  'toyota',
  'volvo',
  'ointment',
  'tablets',
  'sport-brella',
  'grease',
  'breathalyzer',
  'shelfie',
  'clorox store',
  'clorox',
  'delta store',
  'delta',
  'pandemic',
  'asmodee',
  'repos production store',
  'crossbody',
  'mouse',
  'duo',
  'grip strength trainer',
  'cookie mix',
  'ugg',
  'ugg australian shepherd',
  'dotted journal',
  'journal',
  'bullet journal',
  'bike nook',
  'respironics',
  'brian & dany',
  'resqme',
  'whitening',
  'vitamins',
  'eyebrow',
  'supplement',
  'eyelashes',
  'vitaminns',
  'splint',
  'bubble',
  'cream',
  'smoke daddy',
  'oculus',
  'granite stone',
  'nunchucks',
  'immune',
  'brain',
  'multivitamin',
  'mascara',
  'lash',
  'bleach',
  'maisonovo',
  'sanco industries',
  'matkas',
  'is clinical',
  'sesderma',
  'salcoll collagen',
  'cosrx',
  'serious skincare',
  'harness',
  'wild code',
  'lotion',
  'toothpaste',
  'capsules',
  'paracord',
  'brantmaker',
  'graff',
  'magpul',
  'emergency fire',
  'magpul industries corp.',
  'rotation magnetic',
  'floridarooted',
  'dunkin donuts',
  'reebok',
  'fitto',
  'bonide',
  'cnc machined',
  'cnc',
  'finger splints',
  'coppermine',
  'hair',
  'bioadvanced',
  'miracle-gro',
  'trish mcevoy',
  'rail mount',
  'pins cartridges',
  'shooting',
  'briggs and stratton',
  'pull ups',
  'rail',
  'choke',
  'weaver',
  'pgzsy',
  'kimberly-clark',
  'livdry',
  'because',
  'mtm',
  'poitcto',
  'collapsible',
  'siren',
  'e. mishan & sons, inc.',
  'bhh llc',
  'inhaler',
  'vivelle',
  'granitestone',
  'serum',
  'brightening',
  'asterwood',
  'sonew',
  'donginbi',
  'easydew',
  'bio-oil',
  'flowtron',
  'iodine',
  'calvin klein',
  'ledaou',
  'lazora',
  'ostomy',
  'enema',
  'supplyment',
  'lip',
  'balm',
  'toppik',
  'fuller hair',
  'hair fibers',
  'tactical survival gear',
  'sol de janerio',
  'sol de janeiro',
  'defender',
  'glass breaker',
  'rooting',
  'l\'oréal',
  'habitrol',
  'dr. dan\'s',
  'lip balm',
  'chapped lips',
  'chapped lips',
  'l’oreal',
  'flux phenom',
  'shaotong',
  'zymox',
  'traffic advisor',
  'all natural advice',
  'kills germs',
  'white iodine tincture',
  'antiseptic',
  'bluemello',
  'bluesnail',
  'retinol facial serum',
  'carbamide peroxide',
  'antibiotic ointment',
  'thread protector',
  'antihistamine tablets',
  'allergy relief tablets',
  'timoou',
  'taco vs burrito',
  'havasu',
  'vaseline',
  'chap-ice',
  'oralabs',
  'matryoshka nesting dolls',
  'vintage incandescent light bulbs',
  'health bloom inc.',
  'bottle jack buddy',
  'covergirl',
  'jello',
  'kraft heinz',
  'kraft foods',
  'jell-o',
  'sandals',
  'slippers',
  'go hang it!',
  'kurkdjian',
  'maison francis kurkdjian',
  'maison francis kurkdjian',
  'naked',
  'chapstick',
  'bicmte',
  'purple innovation, llc',
  'needles',
  'scout',
  'car seat',
  'infiniti',
  'cervical neck',
  'geomod',
  'snorkel',
  'dummy rounds',
  'meater',
  'apption labs limited',
  'colgate',
  'luer lock',
  'shotgun',
  'firing pins',
  'sonic',
  'sonic anime',
  'sega corporation',
  'ab roller',
  'trtl',
  'sega',
  'game console',
  'wii',
  'rifle bipod',
  'microneedling pen',
  'foot pads',
  'mask',
  'tiny tendo handheld game console',
  'tiny tendo handheld game',
  'video game',
  'smoke tinted',
  'license plate',
  'license plate cover',
  'soft girl rag doll',
  'foxmind',
  'foxmind group ltd',
  'foxmind store',
  'needle',
  'syringe',
  'quality prime goods',
  'all natural shop',
  'teflon',
  'rinseroo',
  'slipper',
  'magnet building',
  'magnet',
  'helmet',
  'hair serum',
  'imestou',
  'wireless power consortium, inc',
  'qi',
  'teeth whitening',
  'power saver',
  'bunny',
  'water doodle mat',
  'hertel wax',
  'hertel & co inc',
  'mini camera',
  'hotelspa',
  'interlink products international, inc.',
  'melissa',
  'melissa & doug, llc',
  'ccs chicago canvas & supply',
  'handheld game console',
  'entertainment software association',
  'batman logo',
  'roku remote',
  'amvr',
  'meta platforms, inc.',
  'facebook, inc.',
  'gorilla tag',
  'oculus quest',
  'syringes',
  'ab mill llc',
  'michael domesick ab mill llc',
  'halloween',
  'buttock',
  'emergency strobe lights bar',
  'progressive multifocal blue light blocking computer glasses',
  'ems',
  'electrical muscle stimulation',
  'elevate',
  '335090062342',
  'dodge ram',
  'challenger chrysler',
  'fiat chrysler',
  'paint puck',
  'the bucket',
  'bucket bag',
  'omperio',
  'nd products inc',
  '99.9% germs',
  'christmas',
  'beads',
  'face mask',
  'octopus baby toys',
  'magnetic blocks',
  'oxygen',
  'oxygen',
  'oxygen cannula',
  'oxygen supply tubing',
  'kills 99.9% germs',
  'bleach gel',
  'toilet bowl cleaner',
  'clear license plate cover',
  'mold remover gel',
  'turmeric',
  'madical device',
  'leg bag',
  'simplissafe, inc',
  'injection syringes',
  'micro',
  'yanscian',
  'plush',
  'cock',
  'anal',
  'shoes',
  'sex',
  'electric gel ball blaster',
  'usb',
  'easy electronic wipes - kills 99.9% germs',
  'seat belt buckle',
  'teeturtle',
  'the original reversible octopus plushie',
  'zero ultra energy drink',
  'pen syringe',
  'snappower',
  'green tea mask stick',
  'ototo design ltd',
  'microcurrent face device roller,',
  'carol cole company dba nuface',
  'legendary whitetails',
  'diabetic pen needles',
  'duck',
  'prepared hero',
  'prepared hero store',
  'pomsare',
  'car buckles',
  'hario co ltd',
  'tinted license plate covers',
  'bike helmets',
  'magnetic dart board',
  'elegant clover necklac',
  'kbc capital llc',
  'yeti coolers, llc',
  'powerful hemp oil',
  'pipes or any item that references use with marijuana or with illegal drugs',
  'center console organizer tray compatible w/ 2021 2022 2023 tesla model black',
  'center console organizer tray compatible w/ 2021 2022 2023 tesla model black',
  'contact lenses and prescription eyewear',
  'needles, with or without a disposable syringe',
  'pacemakers, heart valves, vascular grafts, ventricular bypass devices, and implantable infusion pumps',
  'oximeters that require a prescription',
  'nebulizers and their accessories',
  'continuous positive airway pressure (cpap) machines',
  'diabetic pen needles - universal compatibility, smooth injection',
  'turmeric face oil - nourishing anti-aging rejuvenating moisturizer',
  'turmeric face oil',
  'hydroquinone',
  'smokey bubble license plate shields',
  'pill presses',
  'selling usps shipping materials',
  'blank rain checks',
  'lock picking tutorials',
  'any license plate covers',
  'hewlett-packard development company l.p (hp )',
  'hp 564 high yield ink cartridges',
  'booster car seat',
  'backless booster car seat',
  'blow or dart guns, flare guns, potato guns, crossbows, tear gas, pepper spray, mace, stun guns, or tasers',
  'burrow bunny rabbit stuffed animal',
  'smoked unbreakable plate shields',
  'smoked license plate shields',
  'smoked license plate shields',
  'magnetic fidget pen',
  'fidget pen|magnetic pen',
  'brickhouse',
  'plate shields',
  'clocky llc',
  'nanda home inc.',
  'nerf',
  'chrysler',
  'morel',
  'buddy tools',
  'superfeet',
  'snapdragon',
  'ford',
  'chevrolet',
  'cadillac',
  'gmc',
  'buick',
  'hamilton-beach',
  'ps5',
  'smart ink',
  'cannabidiol',
  'yeti rambler tumbler',
  'rambler',
  'v60 products',
  'oogiebear',
  'yeti',
  'v60',
  'sud scrub',
  'weatherpro',
  'virbac',
  'fisher-price',
  'black decker',
  'black and decker',
  'black + decker',
  'black & decker',
  'playstation',
  'charizard',
  'skechers',
  'milwaukee',
  'hemp',
  'cbd',
  'macos',
  'ios',
  'ipad',
  'samsung',
  'revlon',
  'milwaukkee',
  'mfi-certified',
  'lightning',
  'mroalk',
  'dsi xl',
  'ds lite',
  '2ds',
  'nds',
  '3ds',
  'michael kors',
  'zip top',
  'crown cookware',
  'square',
  'monet beauty products ltd.',
  'ray squad',
  'bumkins finer baby products',
  'brother toner cartridge',
  'pyle',
  'wrist-rocket',
  'uboxes, llc',
  'amosting',
  'the neck hammock',
  'z-man fishing products, inc.',
  'younghair ab ltd',
  'yamaha corporation of america',
  'würth srl',
  'wisdom of the ages',
  'vitagene, inc',
  'tüv süd',
  'tüv markenverbund e.v',
  'tommy hilfiger licensing bv',
  'things 4 strings llc',
  'thea gouverneur bv',
  'the richemont group',
  'the juice plus+ company',
  'the himalaya drug company',
  'technopack corporation (jorestech)',
  'teami blends',
  'swing set stuff',
  'swanson health products',
  'surgi corp',
  'superior products usa llc',
  'supacaz',
  'siser',
  'sd biotechnologies',
  'savvy turtle inc',
  'ryohin keikaku co.,ltd. - muji',
  'rondofile',
  'rc williams company',
  'ram cleaner',
  'quanovate tech, inc. - mira',
  'proactiv company sárl',
  'prescott plastics, llc',
  'pocket radar, inc.',
  'plarium global ltd',
  'peppadew international',
  'peachpopsclipart™',
  'patmont motor werks/go-ped®',
  'patch collection, llc',
  'one two cosmetics, llc',
  'öko-tex',
  'nutrafol - nutraceutical wellness, inc.',
  'national board of medical examiners - nbme®',
  'nailrenew corp.',
  'ministero delle politiche agricole — icqrf',
  'market muncher llc - home intuition',
  'manhattan toy company',
  'luxeavant innovations',
  'lip ink® international',
  'liberta co., ltd. dba baby foot usa',
  'level terrain llc dba flipbelt',
  'lay-n-go, llc',
  'klaire labs',
  'kenrico ltd.',
  'isw trading pty. ltd.',
  'ironmind enterprises, inc.',
  'huggaroo',
  'hong kong proster trading limited',
  'hids4u®',
  'great bay home',
  'goetze\'s candy',
  'global healing center',
  'fourgreen auto parts',
  'fit and glow inc.',
  'fédération internationale de football association (fifa)',
  'fc bayern münchen',
  'ellison educational equipment, inc. - sizzix llc',
  'dr. marty - animal ambassadors, llc',
  'donmar enterprises, inc. - skyroof®',
  'desco corporation',
  'delorean motor company',
  'crochead pty ltd',
  'core survival, inc.',
  'confederate motorcycles llc',
  'comité champagne',
  'comité georges mathieu',
  'chloé',
  'charmed creations llc',
  'chandler tool',
  'celebrate vitamins',
  'cdf firefighters / cal fire local 2881',
  'carlstar group – itp and carlisle brands',
  'carleon',
  'brother international',
  'braniff airways, incorporated.',
  'biomic sciences, llc',
  'bg soflex, llc',
  'ben kaufman sales co.',
  'bemer int. ag',
  'beldt labs',
  'bear grylls ventures llp',
  'autowin.eu ltd',
  'ammodor, llc',
  'agora llc',
  'sinland',
  'foreo',
  'klipsch',
  'yogabody',
  'eccppautoparts',
  'llc dba sunlight supply,',
  'ip holdings',
  'parker eight',
  'discount tens',
  'discounttens',
  'the product hatchery,',
  'nailstar',
  'singer',
  'swisselite',
  't-fal',
  'generic',
  'onix',
  'pokonobe associates',
  'eldaco',
  'jenga game',
  'carino healthcare',
  'westpack shop 3/16" 175 ft x 12" small bubble cushioning wrap, perforated every 12"',
  'hook and loop tape roll strips with adhesive back mounting tape for picture and tools hanging pedal board fastening by jiho',
  'ikea',
  'edepotexpresscs',
  'barvivo',
  'walgroup llc',
  'active brothers aps',
  'wow apple cider',
  'debrief me',
  'stealth',
  'masterark',
  'oojami',
  'matty\'s toy stop',
  'vinyl ease',
  'isle surf and sup',
  'youshiko',
  'quantum networks',
  'controlomatic',
  'aloe cadabra',
  'bafx',
  'brooklyn brownie',
  'access denied',
  'otron',
  'b0734v2dpm',
  'v-cen',
  'solid ventures',
  'vinyl ease llc',
  '183064760552 - professional waiters corkscrew by barvivo - this bottle opener for beer and wine',
  'redict',
  'morella',
  'pacifica technologies inc',
  'ven-ex snake bite kit, bee sting kit, emergency first aid supplies, venom extrac',
  'matty\'s mix-up',
  'taya',
  'zero grid',
  'sierra madre supplies',
  'solid ventures,',
  'lego',
  'taotronics',
  'boosteady',
  'forliver',
  'creatov',
  'nescafe',
  'brightech',
  'procella',
  'drumpf.wtf',
  'wwe raw main event ring',
  'babyliss for men',
  '1byone',
  'utg',
  'hanayama puzzles of japan',
  'make-u-think, inc. dba truro games',
  'make-u-think',
  'mpowerd',
  'vonhaus',
  'ampeg',
  'white collar',
  'new chapter',
  'peroom',
  'dryfhout enterprises, llc dba bakblade',
  'lenox',
  'dba',
  'gibson brands, inc',
  'gibson',
  'funding',
  'aleratec',
  'medcosouth',
  'benefiber',
  'baxter',
  'cosmetics',
  'bare essentials',
  'balm cosmetics',
  'baire bottles',
  'babyliss',
  'ansr',
  'omiera',
  'the noodley',
  'omiera labs',
  'renegade gk',
  'joking hazard llc',
  '3m oral care',
  'promescent',
  '3m deutschland gmbh',
  '3m',
  'jmitoo',
  'tyme llc',
  'vxi',
  'vxi blueparrott',
  'gn netcom',
  'amope',
  'aidance skincare',
  'ahava',
  '1 body',
  'marvel',
  'iottie',
  'digital innovations',
  'monoprice',
  'geri-sleeve',
  'seventh generation baby diaper',
  'zookie',
  'glovework',
  'sterilite',
  'titleist',
  'in-a-bag',
  'global-keratin',
  'gkhair',
  'learherman',
  'aguacatina',
  'tuffy',
  'quickcinch',
  'hitchmate',
  'clarisonic',
  'pursonic',
  'ps3',
  'nicorette',
  'cees',
  'aerogarden',
  'closet complete',
  'wild thera',
  'iris',
  'gemstone',
  'pu leather',
  'prodiana',
  'similac',
  'premium gallery',
  'duffel',
  'garnier',
  'techcomm',
  'lipo-6',
  'presidio',
  'dumbbell',
  'safiveih',
  'duvet',
  'sight',
  'troy',
  'meprolight',
  'serrated',
  'command arms',
  'carbine',
  'crosman',
  'faces of death',
  'aminexil',
  'burris',
  'gas block',
  'barska',
  'ak47',
  'hogue',
  'beretta',
  'mre',
  'warne',
  'millet',
  'nikon',
  'porcelana',
  'nadinola',
  'pbpk',
  'self defense',
  'pepper spray',
  'enfamil',
  'tylt',
  'gomoji',
  'mackie',
  'srixon',
  'wacom',
  'braven',
  'oaklyn',
  'bryo llc',
  'resmed',
  'paris presents incorporated',
  'arc\'teryx',
  'triple cs supplements',
  'alta',
  'akna',
  'wandeneng',
  'soles2dance',
  'flex tape',
  'b01mueuxtw',
  'newbalans',
  'the bradvica company',
  'everlast',
  'hepheas',
  'dental health essentials',
  'pilestone',
  'trafellows',
  'kronify',
  'kronify®',
  'kronify ®',
  'ctron21',
  'brown bear',
  'makita',
  'nitewatch',
  'simple fit',
  'kerastase',
  'dermawand',
  'formufit',
  'sani stick',
  'teeter',
  'bullet',
  'as seen',
  'medline',
  'solascape',
  'cobra',
  'acc u rate',
  'joy baby',
  'dream water',
  'gopro',
  'voron',
  'mato hash',
  'kinetic sand',
  'usa toyz',
  'otc',
  'rdz',
  'ecotools',
  'sheetworld',
  'fuze chicken',
  'zantech',
  'frozen dessert',
  'x-senkry',
  'prompter',
  'trident',
  'mato & hash',
  'talon',
  'noodley\'s',
  'konikit',
  'foreo luna',
  'traeger',
  'kattee',
  'umtele',
  'epauto',
  'flipside wallets',
  'ctron21®',
  'puracy natural',
  'puracy',
  'electronic temperature instruments ltd',
  'thermapen',
  'bekilole',
  'ellura',
  'zepp',
  'burn hd',
  'pharmatoka',
  'green bracket',
  'zepp labs',
  'egg sitter',
  'hemptouch',
  'f & f stores',
  'deco express®',
  'deco express',
  'fening',
  'ctybb',
  'pantheon',
  'lelong',
  'walcase',
  'cedar brands',
  'apple watch band',
  'lg lt700p',
  'herschel',
  'lily\'s lights llc',
  'grohe',
  'venjoin.com',
  'homeopathy world',
  'case-mate',
  'pipetto',
  'essential marine products',
  'brother',
  'strenco',
  'paula deen',
  'venalisa',
  'lure cupping',
  'lilbetter',
  'timbuk2',
  'lady makeup',
  'shop vac',
  'premium led tactical flashlight kit',
  'tactical rescue pocket knife',
  'ematic',
  'revenge',
  'amabrush',
  'dba boricap',
  'ke health llc',
  'learn yoga at home',
  'can\'t live without it, inc',
  'graco',
  'graco inc',
  'mustool®',
  'plexus',
  'plexus worldwide',
  'dymatize enterprises, llc',
  'sientra, inc',
  'outlogiq',
  'purest naturals',
  'tribord',
  'carista',
  'cleenbo',
  'vinyl',
  'matcha 108',
  'hollywood racks',
  'giro',
  'giro launch',
  'dymatize',
  'eventronic',
  'boyko',
  'protool',
  'gusti',
  'focus t25',
  'hurricane spin',
  'damiando',
  'smellfree cat',
  'bounce for beginners',
  'microplane',
  'sunnors',
  'barkoutfitters',
  'new s\'well',
  'warmawear',
  'mopnado',
  'instyler max',
  'babe lash eyelash serum',
  'babe lash',
  'velcro closure',
  'what do you meme, llc',
  'fjerry',
  'solemates',
  'armani',
  'wahl',
  'star wars',
  'lumentics',
  'joy celebrations',
  'miss to mrs natural burlap banner',
  'masta plasta limited',
  'clipart design usa',
  'tanner',
  'kulkea',
  'jonsnow',
  'sout',
  'mad about organics',
  'senrob',
  'b06xg3248k',
  'thin optics stick',
  'joking hazard',
  'deepline',
  'yowei',
  'epson america, inc.',
  'emsoninc',
  'e. mishan & sons, inc',
  'thinoptics',
  'vitazoo',
  'fitbit alta',
  'egyptian magic',
  'oster',
  'rubbermaid',
  'liwacs',
  'polycom',
  'sigma enterprises llc',
  'igeress',
  'kent displays',
  'penrazor',
  'parblo pearl',
  'paw patrol',
  'kictero',
  'air dragon',
  'wacom intuos',
  'kronenburg',
  'elektroden pads',
  'klebeshop24',
  'carino',
  'habor',
  'eccpp',
  'dazi',
  'gear4',
  'gear4 hk limited',
  'sukoa',
  'grundig',
  'lights4fun',
  'pur rf',
  'cadeau@t-online.de',
  'vinani',
  'adidas',
  'stylebreaker',
  'l\'oreal',
  'luckies of london ltd',
  'la ren',
  'rolllra',
  'sbg revo',
  'bark outfitters',
  'seatosummit',
  'sea to summit',
  'gymworld',
  'magformers',
  'drei schwerter',
  'mobil car oil',
  'mobil thynthetic oil',
  's’well',
  'bellefit',
  'can\'t live without it, inc.',
  'tre milano, llc',
  'bellefit, inc,',
  'oopsix',
  'vanage',
  'wagberry',
  'ashley electric',
  'le creuset',
  'tw steel',
  'cobra radio',
  'lion mane dog costume',
  'stokke',
  'inglesina',
  'kitchen aid',
  'pratico goods',
  'pratipad',
  'rocky mountain vacuum',
  'prolux',
  'upanaway',
  'resort sleep',
  'live and sleep',
  'harmon',
  'international watchman',
  'great healthworks',
  'omegaxl',
  'carrera',
  'luxottica group',
  'stanaley',
  'lumunu passion products',
  'limuwa',
  'k&s artisan',
  'total tea',
  'coobey',
  'ergotopia',
  'troy indrustries',
  'wix',
  'top dog chews',
  'euro-pro',
  'goliath',
  'chemical guys',
  'daniel wellington',
  'zadro product inc',
  'lelo - leloi ab.',
  'totaltea_us',
  'xelotech',
  'akribos',
  'mounty',
  'wintex',
  'bearded ben',
  'donnerberg®',
  'donnerberg',
  'aleppo',
  'valneo',
  'pretex',
  'shavette',
  'jbl',
  'cpap',
  'wellb4',
  'ultrasport',
  'ultratec',
  'levivo',
  'ultranatura',
  'phatmojo',
  'paradise toys',
  'excelvan',
  'slidebelts',
  'frozen dessert supplies',
  'ronaqua',
  'sy xiongdi',
  'foreo ltd.',
  'lamphus',
  'revo',
  'iphone',
  'simpeak',
  'eurmax',
  'hook-eze',
  'live and sleep, llc (dba resort sleep)',
  'ultradent',
  'opalescence',
  'dental health essentials llc',
  'fitbit blaze charger',
  'image skincare',
  'cuddlebug',
  'nespresso inissia espresso',
  'robotlife',
  'baby einstein',
  'baby banana',
  'bissell',
  'whirlpool properties, inc.',
  'fairwin',
  'superior glutes',
  'chill gorilla',
  'venjoin.com llc',
  'braketeer',
  'davaon',
  'urbane men',
  'eurmax canopy, inc',
  'buy decorative film',
  'jaimie jacobs',
  'move2play',
  'matcha',
  'urcover®',
  'mobilefox®',
  'mobilefox',
  'iprotect®',
  'iprotect',
  'brush hero',
  'wearme pro',
  'by matcha 108',
  'ergobaby easy snug infant insert',
  'swarovski ag',
  'superior abohone',
  'cacuss',
  'soclean',
  'fooing',
  'dörrwerk',
  'product design patent',
  'car seat footrest',
  'kneeguardkids',
  'duplo',
  'casio',
  'hands free magnetic screen door',
  'astatic',
  'ambiente',
  'drano',
  'clr',
  'doctor drain',
  'instant power',
  'liquid plumr',
  'liquid-plumr',
  'drain out',
  'clog remover',
  'drain opener',
  'first force',
  'whink',
  'bicol',
  'l\'oreal s.a.',
  'sbg revo holdings llc',
  'ancient nutrition',
  'xujinhao',
  'shells',
  'converse',
  'urcover',
  'jetechdesign',
  'cocktailier, llc',
  'cocktailier',
  'buydecorativefilm',
  'practico outdoors',
  'blooming bath',
  'xpose safety',
  'tpc',
  'decathlon',
  'vyncs',
  'tecaroo',
  'peppa pig',
  'kk music store',
  'mendini',
  'asimoon',
  'artis',
  'kayiwa limited',
  'artnaturals',
  'by california basics',
  'oxa 10 cups pitcher water filter',
  'pur',
  'dremel rotary tool',
  'surplus deal usa',
  'orb life sciences',
  'honb',
  'star trek next gen mugs - sciences',
  'star wars hoth dinner set',
  'anker',
  'sparkles make it special',
  's\'well',
  'swell',
  'jenga',
  'kwmobile',
  'viahart',
  'britelites',
  'jetech',
  'anviker',
  'jtrim',
  'philips electronics',
  'zento',
  'trillium',
  '162751656526 - 2" thick fat grips - made from comfortable and durable non-slip silicone rubber',
  'at-a-glance',
  'maximal power',
  'norwex',
  'chemo cap',
  'implus',
  'fitdeck',
  'sof comfort',
  'apara',
  'airplus',
  'little hotties',
  'maxxdry',
  'icetrekkers',
  'dryguy',
  'yaktrax',
  'sneaker balls',
  'fuelbelt',
  'harbinger',
  'triggerpoint',
  'balega',
  'spenco',
  'sof sole',
  'wod toys',
  'dreamwear and cpap',
  'cuisinart',
  'lelo',
  'cruzee',
  'lebra',
  'astro pneumatic tool',
  'nissan',
  'hurricane',
  'wonder home gardens - whg',
  'telebrands',
  'blitzwolf',
  'phallosan',
  'intex',
  'axion',
  'snowera',
  'rustler',
  'latupo',
  'spirid creation',
  'jdmspeed',
  'nutrex',
  'rapid.lash',
  'tyger',
  'mederma',
  'chalktalk sports',
  'the gro company',
  'aduro',
  'ashley black\'s fasciayoga',
  'fascia nation',
  'make fascia great again',
  'pray and slay',
  'blastersquad',
  'blaster',
  'celluliteblaster',
  'faceblaster',
  'after blaster',
  'blaster oil',
  'billionaire healthcare',
  'the cellulite myth',
  'fasciablaster',
  'carelax',
  'teebereiter',
  'clay in motion',
  'shadow river sales',
  'gex worldwide',
  'lad hermes',
  'cityback',
  'twilly d\'hermes',
  'mors de bride',
  'h d\'ancre',
  'constance',
  'sac a dépêches',
  'fourbi',
  'cabalicol',
  'illico',
  'barda',
  'egée',
  'bolide',
  'roulis',
  'steeple',
  'centaure',
  'catenina',
  'petit h',
  'h n e w s',
  'birkin',
  'kellybag',
  'carabas',
  'arion',
  'objet voyageur nocturne indispensable',
  'ovni',
  'voyage d\'hermes',
  'birkin shoulder',
  'kelly shoulder',
  'clou de selle',
  'jypsiere',
  'les ailes d\'hermes',
  'hermes editeur',
  'carrimi',
  'good news',
  'silkycity',
  'h hermessence collection brin de réglisse',
  'angularizer',
  'ashomie',
  'pet ninja',
  'edenware',
  'petninja',
  'dhld',
  'starrich',
  'm2 distribution ltd',
  'deluxe aqua lube',
  'lifetek',
  'blankietails',
  'gex',
  'tweexy',
  'station 22',
  'paris presents',
  'real techniques',
  'lumunu deluxe',
  'deluxe body',
  'deluxe',
  'deluxe aqua',
  'carbocage',
  'carbocage keycage',
  'levivo pet',
  'yoga toes',
  'llc dba adb interests',
  'ashley diana black international holdings',
  'topnotch designs us',
  'woombie',
  'refrigiwear',
  'accuteck',
  'lionsmen',
  'dream like',
  'cfsds',
  'brushhero',
  'kaze',
  'fintie',
  'coosa',
  'b.k.licht',
  'fat gripz',
  'aikou',
  'joyfay',
  'joyfay®',
  'b00denv72k',
  'totaltea',
  'bodysocks',
  'amenitee',
  'kapmore',
  'solmate socks',
  'kaz',
  'hermes',
  'olaplex',
  'de´ longhi',
  'turban plus',
  'bella scarf',
  'car cane',
  'tristar products',
  'uspackshop',
  'talinu',
  'captainki',
  'arilux',
  'articlings',
  'genuine by eiission',
  'eiission',
  'hangerworld',
  'sanddisk',
  'vidal sassoon',
  'aussie',
  'clairol',
  'era',
  'cheer',
  'dreft',
  'safeguard',
  'luvs',
  'puffs',
  'mr clean',
  'ace',
  'ivory',
  'joy',
  'ariel',
  'orb life sciences llc',
  'broadway',
  'woldoclean',
  'movit',
  'quickmount',
  'wicked chili',
  'glass of vennice',
  'amapodo',
  'procave',
  'masonicbuy',
  'moko',
  'treat my feet',
  'swimbest',
  'whirlpool',
  'watch tower bible and tract society of pennsylvania',
  '253111318226',
  '252919355403',
  'zesproka',
  'adafruit',
  'summer infant',
  'sinopuren',
  'adafruit industries, llc',
  'rinhoo',
  'peng',
  'clouds',
  'honeycat',
  'sevenhills wholefoods',
  'vip products',
  'electriduct inc',
  'cratsman',
  'forum novelties',
  'mr coffee',
  'scaredy cut',
  'gourmeo',
  'velcro brand',
  'invisible dog fence',
  'adeept',
  'smoke blaster',
  'homecube',
  'teak shower',
  'rachael ray',
  'carburetor adjustment tool',
  'arburetor adjustment tool',
  'slim xtreme',
  'burei',
  'focuspet',
  'com-four',
  'com-four vertriebs gmbh',
  'monkey mountain',
  'phantom',
  'wodtoys',
  'wod',
  'creative fitness',
  'velcro industries b. v',
  'durex pleasure ring',
  'frux home and yard',
  'dreamwork',
  'rubiks cube',
  'lure essentials',
  'british american innovations',
  'dr. marten\'s',
  'fuji natural',
  'vacnite',
  'jabra',
  'sky viper',
  'robert bosch llc',
  'aduro sport',
  'meland',
  'panasonic',
  'vikingstrength',
  'grupo rs',
  'aira brand',
  'vaunn',
  'poly and bark',
  'unker\'s',
  'segmart',
  'hario',
  'halio',
  'kalita',
  'scotabc',
  'melissa & doug',
  'fyshflyer',
  'adore by nat',
  'abcuts',
  'bouch',
  'ktm',
  'uni',
  'doterra young living',
  'polished gentleman',
  'utopia kitchen',
  'utopia',
  'netatmo',
  'top greener',
  'topgreener',
  'wenfeng',
  'hompo',
  'nifty nozzles by sugar and crumbs',
  'degbit',
  'arancinotto',
  'hcctoo',
  'meco',
  'oral b',
  'nizoral',
  'barello uk',
  'lone cone',
  'craftsman',
  'hi-bagz',
  'bean bag bazaar',
  'echo',
  'diane',
  'ann summers',
  'fh group',
  'orobay',
  'uggs',
  'red copper',
  'hexin',
  'luckies of london',
  'ugears',
  'mier',
  'innovo deluxe',
  'beakey',
  'songmics',
  'herbalife',
  'pk green',
  'hane',
  'liberty imports',
  'silicon beauty blen',
  'sanggol',
  'pratico kitchen',
  'reanice',
  'sir perky',
  'telebrands corporation',
  'velcro industries',
  'pestbye cat repellent',
  'opticron',
  'primrose',
  'the perfect cosmetics company',
  'vena',
  'topmax',
  'minecraft',
  'zulu bunch of baloons',
  'eloi',
  'duracell',
  'decowall',
  'higher nature',
  'rivers of health',
  'club petz',
  'joe foreman',
  'indian arts',
  'btw enterprises',
  'inflatablesgiant',
  'yens elite',
  'spy crushers',
  'biosun',
  'easewax',
  'card boy',
  'performix',
  'rhino',
  'hunter',
  'poshland',
  'bigmouth',
  'bulbhead',
  'shunzaor',
  'giraffe',
  'timex',
  'imex',
  'ares',
  'tanita',
  'true',
  'innovo',
  'carchain',
  'uboxes',
  'tacvasen',
  'smarterfresh',
  'pivkey',
  'suntana',
  'suntana spray tan',
  'soyoko',
  'gablemere ltd',
  'greenhurst',
  'qifit',
  'arbitron global',
  'bubble wrap',
  'body sculpture',
  'lihao',
  'american weigh',
  'sealed air corporation',
  'super sunnies',
  'homekey',
  'foodvacbags',
  'moonrays',
  'fasmov',
  'fiskars',
  'breville',
  'zyliss',
  'zen water filter',
  'monster cable',
  'altruism',
  'dihl',
  'dell',
  'save n save',
  'stanley',
  'camco',
  'kensie',
  'asin:b01hslsotc, b01n2gw4ty',
  'barrettine',
  'john mills limited',
  'jml ltd',
  'the glowhouse ltd',
  'chalkboard',
  'blue gentian, llc',
  'blue gentian',
  'gardspo',
  '3sprouts',
  'mecolletion',
  'nuzamas',
  'solwise',
  'easehold',
  'a-szcxtop',
  'creative technology ltd',
  'cloud nine',
  'mr blanc teeth',
  'oase ltd',
  'oase (uk) ltd',
  'oase',
  'kitchenaid',
  'toorun',
  'uzitec',
  'lillian ruff',
  'zxz',
  'zuru ltd',
  '66fit',
  'worx',
  'meika',
  'meika ltd',
  'pestbye',
  'scs',
  'dasco pro',
  'brutus',
  'sure plug',
  'been5le',
  'goo baby',
  'maketheone',
  'fitness anywhere',
  'kari-me',
  'natures greatest secret',
  'digital ant',
  'charisma brands, llc',
  'optimised energetics',
  'speck products',
  'fitbit',
  'loveblue',
  'zenzoi',
  'jml',
  'urban fusion',
  'direct designs',
  'h2o',
  'rust-oleum',
  'flex seal',
  'esc ltd',
  'airwave',
  'trolley bags uk',
  'trolley bags uk ltd',
  'esc',
  'esc europe ltd',
  'luxsego',
  'robinson',
  'jack sealey',
  'sealey',
  'sushi bazooka',
  'amzdeal',
  'drive medical',
  'neue design',
  'rdx amara',
  'ev cables',
  'mellanni',
  'grill griddles',
  'grillaholics',
  'ab flex',
  'bon aire',
  'mora',
  'laphroaig',
  'rdx',
  'rdx inc',
  'rdx inc ltd',
  'dba 3 sprouts',
  'grenadine apparel inc',
  'beautiful beanbags',
  'beautiful beanbags limited',
  'pharmedoc',
  'huele',
  'hydroluxe',
  'zacurate',
  'innoo tech',
  'nokia',
  'lenovo',
  'motorola',
  'beardeur',
  'bosch',
  'rolson',
  'unicorn cosmetics',
  'bazooka',
  'petsafe',
  'pedalpro',
  'tech traders',
  'keysmart',
  'aftershokz',
  'gotham steel',
  'eyes of india',
  'big mouth',
  'nutri ninja',
  'knive',
  'mora companion',
  'lumunu',
  'nite ize',
  'omyfilm',
  'es distributions llc',
  'cuisinart sunbeam oster krups',
  'enfagrow',
  'baby and brooke',
  'mutbak durango',
  'super power supply',
  'pet eden',
  'idash',
  'knives',
  'victorinox',
  'clarins',
  'neal bearings',
  'bouffe',
  'basilica botanica',
  'euphoria',
  'lakeland',
  'blaupunkt',
  'alps',
  'neca',
  'genius gmbh',
  'rob dyrdek',
  'leatherman',
  'funace',
  'elf stor',
  'nik',
  'james bond',
  'mothercare',
  'trainingmask',
  'one1x',
  'rosotena',
  'b06xwkmd4r',
  'bushnell',
  'jordan',
  'cable matters',
  'puma',
  'conair',
  'disney',
  'eco4us',
  'bell',
  'spigen',
  'velcro',
  'suddora llc',
  'humble chic ny',
  'velcro industries b.',
  'gablemere',
  'bedtime pal',
  'play platoon',
  'neiko',
  'mybeautycc',
  'beautycc',
  'talavera hair products',
  't3 micro inc',
  'sara noon',
  'sonyplastation',
  'moro led clip aquarium lights',
  'grenco science inc.',
  'velcro industries b. v.',
  'armorsuit',
  'pinty',
  'cokaka',
  'cuppa mix',
  'ninepeak',
  'exoterra',
  'sealed air',
  'california home goods',
  'carburetor adjusting tool kit',
  'hooai',
  'pmd',
  'bodyorbit',
  'mkono',
  'fluval',
  'echo dot',
  'ghome',
  'hagen',
  'nato',
  'scotch',
  'popsockets',
  'pro tech',
  'letmy',
  'hausbell',
  'puregrace',
  'spiralife',
  'marshal black',
  'spatula',
  '321 strong',
  'catit',
  'lamaze',
  'rolf c. hagen, inc',
  'moichef',
  'tekcoo',
  'lift',
  'muscle blast',
  'oxgord',
  'norton',
  'watch ya mouth',
  'i-unik',
  'maxxima',
  'yum! brands inc.',
  'your baby can llc.',
  'younique llc',
  'y amp;t meniketti',
  'x mini capsule speakers',
  'www.snakeemporium.com',
  'www.danworkshop.com',
  'www.cutecolors.com',
  'world wrestling entertainment inc. wwe',
  'world hockey association llc',
  'windmill parts.com',
  'wiggles touring pty limited',
  'whizardries inc.',
  'whelen engineering company inc.',
  'wd music products inc.',
  'water pik inc',
  'vivint inc.',
  'vintage fans l.l.c.',
  'vanguard industries inc.',
  'ursula hock henschke',
  'united states forest service usda',
  'ultimate creations inc./ ultimate warrior/warrior',
  'ugg holdings inc.',
  'treasured hungarian family recipestm',
  'trainingmask llc',
  'tori richard ltd.',
  'tom kelley studios inc.',
  'tmh technology co. ltd.',
  'tiger tom pistone race cars amp; parts',
  'tiffany amp; company',
  'thread a bead',
  'technical video llc',
  'technica usa moon boot',
  'team mysterio inc.',
  'taser international inc',
  'tamiya america inc.',
  'tad bits baby items and more llc',
  'swiss army brands inc.',
  'spyder active sports inc.',
  'spicer pro llc',
  'southwest pictures / southwest entertainment group llc',
  'sole technology inc.',
  'software amp; information industry association siia',
  'snugglycat incripple rug',
  'snb react ne rlands',
  'snap on incorporated',
  'sms audio llc',
  'smartsound software inc.',
  'smarterfresh llc',
  'skiboards superstore inc.',
  'siesco international limited',
  'shimano inc',
  'seeing with soundvoice',
  'secret of art',
  'scrolling license plate patent infringement',
  'savanna group ltd savanna samson',
  'sanyo electric co. ltd.',
  'salt life holdings llc',
  'rodan + fields',
  'rocket science institute inc.',
  'relix international inc.',
  'red steagall #039;s cowboy corner',
  'red monkey designs inc.',
  'red hat society inc',
  're/max international inc.',
  'ranger doug #039;s enterprises',
  'randomwalk llc',
  'radiancy inc.',
  'quiksilver inc',
  'provo craft amp; novelty inc.',
  'pratico goods llc',
  'polymorphe inc',
  'plumeria bay inc.',
  'ploom pax labs',
  'playtex products llc',
  'platypus wear inc. dba bad boy brands',
  'piperwai llc',
  'philosophy inc.',
  'pevonia international llc',
  'patmont motor werks/go ped',
  'pagedown technology llc',
  'pacific market international llc',
  'p rogers inc.',
  'orthotebb health shoes llc',
  'origami owl llc',
  'opi products inc',
  'old amp; urban',
  'oakley inc.',
  'nsk americas inc.',
  'nordstrom inc.',
  'nickolas muray photo archives llc',
  'netpicks llc',
  'national board of medical examiners nbme',
  'national academy of television arts amp; sciences',
  'n.v.e. inc.',
  'motion picture association of america mpaa',
  'mooneyes usa inc.',
  'moni originals',
  'merle norman cosmetics inc.',
  'medcosouth healthcare llc',
  'mars inc.',
  'marianne #039;s sol mate socks inc.',
  'mad dogg athletics inc.',
  'luxottica retail',
  'luxe jewels llc dba stella amp; dot',
  'light amp; dark productions',
  'lifted research group inc. l r g',
  'lifeproof treefrog',
  'levi strauss amp; co.',
  'leupold amp; stevens inc.',
  'lenny and eva inc.',
  'laser design int #039;l llc',
  'larry hartsell seminars inc.',
  'langley productions inc.',
  'kronemann design studio pty. ltd. house of kronemann usa',
  'knowledge in motion inc.',
  'king technology inc.',
  'kenu inc.',
  'kate spade amp; company',
  'k.w. muth company inc.',
  'js amp;m sales amp; marketing inc.',
  'joy kroeger beckner classical realism from hounds to humans',
  'jordan design studio',
  'jet performance products inc',
  'jacket4bikes',
  'intuit inc.',
  'incipio technologies inc.',
  'hybrid systems ltd. inc. hsl',
  'human touch llc',
  'horizon hobby inc.',
  'home power inc.',
  'hewlett packard company hp ink amp; toner',
  'hdmi licensing llc',
  'hartley loudspeakers inc.',
  'harley davidson motor company',
  'guthy renker corporation',
  'gunnar optiks llc',
  'grand chapter of phi sigma kappa inc.',
  'gottlieb development llc',
  'gn netcom dba jabra',
  'gibson brands inc.',
  'garmin',
  'gaiam inc.',
  'g. loomis inc.',
  'frito lay inc.',
  'fox twentieth century fox film corporation',
  'fossil inc.',
  'foscam intelligent technology co. ltd.',
  'fleurville florida council of bromeliad societies inc.',
  'fitness brands inc./direct entertainment media group',
  'filemaker inc.',
  'fgm ventures llc dba petpost',
  'federation against copyright ft fact ltd',
  'federal express corporation fedex',
  'fca us llc',
  'farmland foods inc.',
  'facelift ent. inc',
  'estate of marilyn monroe llc',
  'ergo baby carrier inc.',
  'epson america inc.',
  'epson uk corporation',
  'electro harmonix effects',
  'edgar rice burroughs inc.',
  'ecosphere associates inc.',
  'eclipse records inc',
  'easton sports inc',
  'eames office lucia eames',
  'eagle creek enterprises tim cox fine art',
  'dunlop manufacturing inc.',
  'duke of pearl llc',
  'dropcrate llc',
  'drive in exchange ltd',
  'dr. denese skinscience labs inc.',
  'donmar enterprises inc. skyroof',
  'dolby laboratories inc.',
  'doctor #039;s associates inc. dba subway',
  'dionne quintuplets',
  'digium inc.',
  'diesel london ltd.',
  'dick harrell',
  'dermalogica inc.',
  'delta air lines inc.',
  'dave #039;s discount motors',
  'data professionals',
  'dash america dba pearl izumi inc.',
  'darkhorse ranch inc.',
  'dark horse comics inc.',
  'dansko llc',
  'danes r us great dane amp; pet art',
  'cucusoft inc.',
  'crocs inc.',
  'crocs asia',
  'criswell embroidery amp; design',
  'coway co. ltd',
  'cool mobility johanson nominees pty.',
  'colart americas inc.',
  'coach inc.',
  'cloud b inc.',
  'cloanto italia srl',
  'classic video l.l.c.',
  'chloe',
  'chief architect inc.',
  'chanel inc.',
  'chalk amp; vermilion fine arts',
  'ceranet inc.',
  'cbs entertainment and desilu too llc unforgettable licensing',
  'carrs coins and rocks inc.',
  'carmix gps',
  'carmen #039;s vintage collections',
  'care creations inc.',
  'car freshner corporation',
  'canyon chenille inc.',
  'canon inc.',
  'calutech inc.',
  'bua inc.',
  'browning laboratories inc.',
  'boppy company',
  'bonnie #039;s plants',
  'blockware llc d.b.a. great useful stuff',
  'blackpoint engineering llc',
  'bino products llc',
  'billie w. taylor ii ph.d.',
  'bill owen cowboy artist',
  'benchmade knife company inc.',
  'beachbody llc',
  'baume amp; mercier',
  'b.h.p. inc. dba nialaya jewelry',
  'avedis zildjian co.',
  'automotive technologies inc.',
  'auto meter products inc. autometer',
  'autism speaks inc.',
  'au ntic brands group llc',
  'australian gold inc.',
  'auntie anne #039;s inc.',
  'atlantic research and marketing a.r.m.s.',
  'artbeats software inc.',
  'ariix llc',
  'ansonia records inc.',
  'amybug #039;s attic',
  'amway corporation',
  'americas drive in corp. / sonic corp. amp; subsidiaries',
  'american weigh scales inc.',
  'aleratec inc.',
  'abercrombie amp; fitch',
  'hydro gizmos',
  'bowflex',
  'loreal',
  'magic bullet nutribullet',
  'rfid',
  'iclever',
  'farberware',
  'circulon',
  'meyer',
  'anolon',
  'teeter better back vibration cushion',
  'misuse',
  'cath kidston',
  'magic bullet party bullet',
  'audio technica',
  'albolene',
  'carters',
  'gerber childrenswear llc',
  'sharkninja',
  'sharkninja operating llc',
  'sugru',
  'alex and ani',
  'one tigris',
  'xbmc',
  'kodi',
  'roadpal',
  'meal prep haven 3',
  'skip hop',
  'store your board',
  'mm-beachbody',
  'turbotax',
  'simply fit board',
  'ninja 3in1 mc750',
  'frontline',
  'zosi',
  'atomic beam usa',
  'star shower as seen on tv motion laser lights star projector',
  'taclight',
  'ghb',
  'trx go',
  'renapur',
  'exploding kittens',
  'caseology',
  'fujifilm',
  'wstechco',
  'schulter kerdi-band',
  'sandisk',
  'california basics',
  'citric acid',
  'skip-hop',
  'beauty junkees',
  'cobrabraid',
  'totalpack',
  'compare to avery 51',
  'ammex',
  'marljohns',
  'dr beats',
  'hasbro',
  'freebit',
  'dohomai',
  'la muscle',
  'torro cases',
  'nutri bullet',
  'sketchers',
  'ninja nutri',
  'soundasleep',
  'slendertone',
  'opi',
  'maven',
  'oribe',
  'powerstep',
  'kohbi-inc',
  'pure-wave',
  'owl wonderland',
  'bob',
  'squatty potty, llc',
  'diesel zero plus eau de toilette for men - 75 ml',
  'cutting board bamboo extra juice groove large serving tray kitchen wood butcher',
  'bigmouth inc',
  'ipow',
  'test - dont delete me',
  'ipow easy one touch mini',
  'luvvit',
  'mpow',
  'obagi medical',
  'blazebox',
  'epionce',
  'onekubeddesigns',
  'travelrest',
  'guaranty',
  'refund',
  'travel rest',
  'hamilton housewares',
  'kopylot',
  'grill beast',
  '4knines',
  'insanity workout',
  'high island health',
  'aneros',
  'h&b',
  'vitamix',
  'tokentools',
  'nike italy',
  'hells angels motorcycle',
  'vega 911',
  'the open university',
  'sheridan douglas',
  'pneumaticcomponents',
  'paddington',
  'mike barrett',
  'lynn r. papercrafts',
  'lipsy',
  'kettle foods',
  'land rover',
  'jaguar',
  'hairy rs',
  'ford motor',
  'first great western',
  'first group',
  'chocolate starfish.',
  'fields of the nephilim',
  'carl mccoy',
  'burlen fuel system',
  'blackpoint engineering',
  'americana international',
  'all saints',
  'velux',
  'vkr holding',
  'vidbidness',
  'umbro international limit',
  'ulead systems',
  'transcender',
  'the premier league',
  'dba chefs resource',
  'synergy computing busines',
  'sony ericsson mobile comm',
  'sarah lough',
  'ruth louise dunn',
  'rosetta stone',
  'pronto moda global limite',
  'orlando digital telephone',
  'nizamas gallery',
  'neutrik ag',
  'moosaics',
  'lynda',
  'kai z feng',
  'jayco',
  'jack sealey ltd',
  'id films',
  'george halbert production',
  'fulvio bianconi',
  'fifa',
  'f?',
  'carol ann clarke',
  'trendy fleece tots',
  'annette haydon',
  'ann cooper',
  'a.b. mckinley',
  'zodiac watches',
  't?',
  'playboy',
  'phiten',
  'oko-tex',
  'wuppertal-solingen remsch',
  'industrie und handelskamm',
  'fc bayern m?',
  'bsa',
  'business software allianc',
  'amway',
  'zappos',
  'yubo technology',
  'your baby can',
  'xpressmart',
  'xiangzhiheng electronics',
  'snakeemporium',
  'danworkshop',
  'cutecolors',
  'wwe',
  'world wrestling entertain',
  'world hockey association',
  'windmill-parts',
  'wiggles touring',
  'whizardries',
  'whelen engineering compan',
  'wd music products',
  'water pik',
  'blue ribbon book',
  'walker metalsmiths c',
  'vintage fans',
  'vintage cigarette',
  'victory seed',
  'vickie milazzo',
  'vanguard industries',
  'ultramax products',
  'ultimate sports franchise',
  'ultimate warrior',
  'ultimate creations',
  'ugs corp',
  'ugg holding',
  'trinity',
  'treasured hungarian famil',
  'tori richard',
  'tomei powered usa',
  'tom kelley studios',
  'tokyoflash',
  'tmh technology',
  'time tracker',
  'tiger tom pistone race ca',
  'three dogs and a cat',
  'thread-a-bead',
  'third man',
  'thin blue',
  'weinstein company',
  'siia',
  'the software & informatio',
  'the sewing bee crinoline',
  'the sensual candle',
  'the national academy of t',
  'peter william ham',
  'the heirs and estate',
  'the gretsch company',
  'the ferret company',
  'marilyn monroe',
  'the estate',
  'the collectors addition',
  'tekay designs',
  'techsmith',
  'technical video',
  'moon boot',
  'technica usa',
  'team mysterio',
  'taser international',
  'tamiya america',
  'tad-bits baby items',
  'swiss army brands',
  'swarovski',
  'stussy inc',
  'studiojenkins works',
  'stromberg carburetor',
  'stephen shore',
  'spyder active sports',
  'spicer pro',
  'southwest entertainment g',
  'southwest pictures',
  'sole technology',
  'society for human resourc',
  'snb-react',
  'sms audio',
  'smartsound',
  'skiboards superstore',
  'sigmacumlaude',
  'siesco',
  'sew terific',
  'seeing with sound - the v',
  'scrolling license plate p',
  'schlyer',
  'savanna samson',
  'savanna group',
  'sanyo electric',
  'salt life holdings',
  'sadowsky guitars',
  'rude awakening coffee hou',
  'rocket science institute',
  'rn study',
  'ridgerock',
  'rideworx pty .',
  'richard avedon',
  'rgis',
  'revelation',
  'reminderband',
  'relix international',
  'red steagall',
  'red monkey',
  'red hat',
  'red digital cinema',
  'red bull',
  're/max international',
  'razormaid',
  'rare sportsfilms',
  'ranger doug',
  'randomwalk',
  'radiancy',
  'quiksilver',
  'provo craft & novelty',
  'professorprofits',
  'premiumfishing auctions',
  'practically darling',
  'airbrushs',
  'power art',
  'poppy',
  'polymorphe',
  'plumeria',
  'playtex',
  'bad boy',
  'platypus wear',
  'philosophy',
  'pevonia international',
  'peri k',
  'pen press',
  'peachpopscliparttm',
  'go-ped',
  'patmont motor werks',
  'big pictures',
  'paradise film institute',
  'panasonic corporation of',
  'pampered chef',
  'pagedown technology',
  'pacific market internatio',
  'orthotebb health shoes',
  'orange',
  'opi products',
  'oakley',
  'nordstrom',
  'nintendo',
  'netpicks',
  'national shooting sports',
  'national historic mining',
  'nbme',
  'national board of medical',
  'n.v.e.',
  'my poupette enterprises i',
  'moviecraft',
  'mpaa',
  'motion picture associatio',
  'mooneyes usa',
  'mitchell repair',
  'michelles scrapbooking',
  'merle norman cosmetics',
  'medcosouth healthcare',
  'master of illusions enter',
  'mars',
  'mamiya america corporatio',
  'mad dogg athletics',
  'dba stella',
  'luxe jewels',
  'lip ink',
  'linkedin',
  'l-r-g',
  'lifted research group',
  'lifetrons',
  'treefrog',
  'lifeproof',
  'leupold & stevens',
  'lenny and eva',
  'laser design',
  'las vegas wranglers',
  'larry hartsell',
  'langley productions',
  'lacoste',
  'la chemise',
  'kt magic',
  'kronemann',
  'kleinn automotive accesso',
  'king technology',
  'k.w. muth',
  'hounds to humans',
  'classical realism',
  'joy kroeger beckner',
  'jewelultradiamondbrite',
  'jet performance products',
  'it works marketing compli',
  'intuit',
  'incipio',
  'hsl',
  'abercrombie',
  'air force one air conditi',
  'aircraft technical publis',
  'american school of needle',
  'american weigh scales',
  'americas drive-in corp',
  'amiclubwear',
  'amybugs primitive attic',
  'ansonia records',
  'ar15',
  'artbeats software',
  'atlantic research and mar',
  'a.r.m.s.',
  'auntie anne',
  'austin city limits',
  'klru',
  'australian gold',
  'authentic brands group ll',
  'autism speaks',
  'automotive technologies',
  'avedis zildjian',
  'b.h.p.',
  'dba nialaya jewelry',
  'barnett research and comp',
  'bell helicopter textron',
  'benchmade knife company',
  'billie w. taylor ii',
  'bloomberg',
  'bonnies plants',
  'british phonographic indu',
  'browning laboratories',
  'bua',
  'bug me video',
  'bushnell performance opti',
  'tasco sales',
  'calutech',
  'cameraquest',
  'canadian standards associ',
  'canon',
  'canyon chenille',
  'canyon dancer motorcycle',
  'capt_nemo',
  'round_2brass',
  'care creations',
  'carmens vintage collecti',
  'carrs coins and rocks',
  'caths pennies designs',
  'cbs entertainment',
  'desilu',
  'celebration bar review',
  'ceranet',
  'chalk & vermilion fine ar',
  'chanel',
  'cher-ished treasures',
  'chief architect',
  'classic video',
  'cloanto italia',
  'coach',
  'colart americas',
  'coldwater creek',
  'colnago',
  'cool mobility',
  'johanson nominees',
  'cosanti originals',
  'paolo soleri',
  'cosmic debris',
  'coway',
  'creations',
  'jeannine',
  'creative carvings',
  'monte',
  'criswell embroidery',
  'crochet crafts',
  'helga',
  'crocs',
  'cucusoft',
  'cutco cutlery',
  'danes-r-us great dane',
  'daniel bingham',
  'dansko',
  'dark horse comics',
  'darkhorse ranch',
  'datapro',
  'daves discount motors',
  'dell computer',
  'delta air lines',
  'dermalogica',
  'dick harrell performance',
  'dhpc inc',
  'diesel',
  'doctors associates',
  'donmar enterprises',
  'skyroof',
  'dr. denese',
  'skinscience',
  'dressthatman',
  'drive-in exchange',
  'dropcrate',
  'duke of pearl',
  'dunlop manufacturing',
  'e.i. du pont de nemours a',
  'eames office',
  'lucia eames',
  'easton sports',
  'eclipse records',
  'ecosphere associates',
  'edgar rice burroughs',
  'efbcs feline conservatio',
  'epson',
  'erica skadsen',
  'escort',
  'estate of garry winogrand',
  'etrailer',
  'exeter research',
  'fabjob',
  'facelift',
  'farmland',
  'federal express corporati',
  'fedex',
  'federation against copyri',
  'fender musical instrument',
  'filemaker',
  'fitness brands',
  'fleurville florida',
  'footprints publishings in',
  'foscam intelligent',
  'fossil',
  'frito-lay',
  'gaiam',
  'gaylord',
  'georgia pacific',
  'georgie girl',
  'gerber childrenswear',
  'gibson guitar corp',
  'grand chapter of phi sigm',
  'grand lodge fraternal ord',
  'grandma moses properties',
  'guess and marciano',
  'guthy-renker',
  'harley-davidson',
  'hartley loudspeakers',
  'hdmi licensing',
  'helena lind',
  'home power',
  'horizon hobby',
  'huggalugs',
  'human touch',
  'hybrid systems',
  'proactiv',
  'iso beauty',
  'zumba fitness',
  'boldloft',
  'black,decker',
  'procter & gamble company',
  'fjerry, llc dba what do you meme, llc',
  'ontel products corporation',
  'e. i. du pont de nemours and company (dupont)',
  'wowwee group ltd',
  'zumba',
  'zip gun',
  'zhao xiang',
  'yankee candle',
  'wyndmere',
  'wubbanub',
  'wow gear',
  'wow cup',
  'william mark',
  'westin',
  'weber',
  'weathertech',
  'vwaq',
  'vtooland',
  'versaliving',
  'vampire squid cards',
  'united pet',
  'ultra herbal',
  'tuft & needle',
  'trx',
  'trunki',
  'true religion',
  'trebco',
  'tommie copper',
  'thule',
  'thermacell',
  'tangle teezer',
  'superchips',
  'stx international',
  'star kids',
  'spin master',
  'speck',
  'sony',
  'snapon',
  'snap-on',
  'slimbelly',
  'simplicam',
  'simplehuman',
  'simple human',
  'sigma',
  'shure',
  'seven towns',
  'sephra',
  'sennheiser',
  'seat belt extender',
  'schwabel',
  'riorand',
  'rigid',
  'reditainer',
  'real flame',
  'razer',
  'philips norelco',
  'paradise galleries',
  'oxo',
  'otter box',
  'nutribullet',
  'now foods',
  'nordic naturals',
  'ninja master',
  'nest',
  'neocutis',
  'nemoba',
  'neewer',
  'nautilus',
  'mypillow',
  'my pillow',
  'moshi',
  'mophie',
  'moen',
  'mishimoto',
  'melaleuca',
  'mcdavid',
  'mavala',
  'manfrotto',
  'magmatic',
  'magic bullet',
  'macneil',
  'lunchbots',
  'lionsgate',
  'linksys',
  'lifevantage',
  'ledglow',
  'law enforcement',
  'kleinn',
  'kimberly-carr',
  'kicker',
  'k&n',
  'jewelry organizer',
  'irobot',
  'iqair',
  'instyler',
  'induction innovations',
  'image vital c',
  'ideal industries',
  'i2x',
  'hypertech',
  'husky liners',
  'hubmar',
  'hp',
  'hoover',
  'hewlett-packard',
  'gu original',
  'grover',
  'grizzly',
  'grenadine apparel',
  'gratiae',
  'goja',
  'goal zero',
  'gerber',
  'frux',
  'forever 21',
  'flare',
  'firearm',
  'ergobaby',
  'ergo baby',
  'edge products',
  'ecosphere',
  'drnatura',
  'dreamline',
  'dre beats',
  'dr. natura',
  'diesel zero',
  'dewalt',
  'delonghi',
  'delaine\'s',
  'deere',
  'de\'longhi',
  'daimler ag',
  'daimler',
  'crystal allies gallery',
  'crabs adjust humidity',
  'cozy sack',
  'columbia',
  'classic ultrasonic aromatherapy diffuser',
  'cisco-linksys',
  'choon\'s design',
  'chazpro',
  'centerforce',
  'cards against humanity',
  'car scenter electric diffuser',
  'cabeau',
  'bumbleride',
  'broadway basketeers',
  'bose',
  'boba',
  'blowgun',
  'big boss',
  'benchmade',
  'belkin',
  'beach body',
  'baby k\'tan',
  'arm\'s reach',
  'arcsoft',
  'antennax',
  'angelynn',
  'amscope',
  'ammunition',
  'ammo',
  'aem',
  '4life',
  '3 sprouts',
  'zephyr vaporizers',
  'zen design group ltd',
  'zappos.com',
  'zamboni',
  'zagg',
  'z produx inc.',
  'yvonne hedley',
  'yum! brands, inc.',
  'yubo technology co.ltd.',
  'your baby can, llc.',
  'younique, llc',
  'yogitoes',
  'y&t - meniketti',
  'xpressmart.com',
  'x-mini capsule speakers',
  'xiangzhiheng electronics inc.',
  'xbmc solutions ltd - droidbox',
  'x bats',
  'wã¼rth srl',
  'wristwidget',
  'worldwide women artists (wwao)',
  'world wrestling entertainment, inc. (wwe)',
  'world hockey association, llc',
  'wonder wizards',
  'with you designs, llc and with you lockets',
  'windmill-parts.com',
  'wiggles touring pty limited, the',
  'whole body research, llc',
  'whizardries, inc.',
  'whelen engineering company, inc.',
  'wh software limited',
  'west frames, inc.',
  'west american corporation d/b/a rbh sound',
  'weinstein company, the',
  'wd music products, inc.',
  'wax liquidizer ltd.',
  'water pik, inc',
  'warner\'s blue ribbon books on swarovski',
  'warner music group',
  'ware family genealogy',
  'walnut studiolo llc',
  'walker metalsmiths celtic jewelry',
  'vortex optics',
  'volkswagen corporation',
  'vkr holding a/s (velux)',
  'vivint, inc.',
  'virgil c. stephens',
  'viper interactive',
  'vintage fans, l.l.c.',
  'vintage cigarette lighters',
  'vietnam international video',
  'victory seed co.',
  'vickie milazzo institute',
  'versace',
  'vera bradley',
  'velcro companies',
  'vanguard industries, inc.',
  'van cleef & arpels',
  'vale science technology co. ltd',
  'vacheron constantin',
  'ursula hock-henschke',
  'university of iowa',
  'united states forest service - usda',
  'uni-trend technology co., ltd',
  'underwriters laboratories, inc.',
  'umbro international limited',
  'ultramax products limited',
  'ultra glow cosmetics ltd',
  'ultimate pet nutrition, llc',
  'ultimate sports franchise agents',
  'ultimate creations, inc. / ultimate warrior / warrior',
  'ugs corp.',
  'ugg holdings, inc.',
  'twinkl ltd',
  'tã¼v sã¼d',
  'tãœv markenverbund e.v',
  'turbosmart',
  'tshirt bordello',
  'treasured hungarian family recipes tm',
  'trainingmask, llc',
  'trailersauce',
  'toughcoins llc',
  'tottenham hotspur ltd',
  'total gym',
  'total family ministries',
  'tori richard, ltd.',
  'top secret recipes',
  'tommy hilfiger',
  'tomei powered usa inc.',
  'tom kelley studios, inc.',
  'tokyoflash japan',
  'tokentools pty ltd',
  'to your home ltd',
  'tmh technology co., ltd.',
  'time tracker technology',
  'tigerdirect',
  'tiger tom pistone race cars & parts',
  'tiffany & company',
  'tidyemu',
  'three dogs and a cat inc.',
  'threadabead',
  'thomas losh',
  'third man records',
  'these please ltd',
  'the lifevantage corporation',
  'the juice plus, company',
  'the jewelry channel inc. dba shop lc',
  'that\'s greenius, llc',
  'tekay designs inc.',
  'tecscan of north florida, inc.',
  'techsmith corporation',
  'technical video, llc',
  'technica usa (moon boot)',
  'team mysterio, inc.',
  'taser international inc.',
  'tania r. chase',
  'tamiya america, inc.',
  'takata corporation',
  'tad-bits baby items and more llc',
  'tactical beard owners club (tboc)',
  'synergetics',
  'symantec',
  'sylver designs',
  'swiss army brands, inc.',
  'swift response, llc',
  'swarovski north america limited',
  'suzhou aobani trading company ltd.',
  'surgical appliance industries, inc.',
  'sunrider international',
  'suncast corporation',
  'summitfashions',
  'sugru (formformform ltd)',
  'sue coffee',
  'stv motorsports llc',
  'stussy inc.',
  'sts industries inc. - nagebee',
  'stromberg carburetor ltd.',
  'stephen shore, photographs',
  'star alliance services gmbh',
  'standard innovation corporation',
  'spyder active sports, inc.',
  'sprint corporation',
  'spicer pro, llc',
  'spicefit',
  'southwest pictures / southwest entertainment group, llc',
  'sony ericsson mobile communications ab',
  'solowork studio',
  'sole technology, inc.',
  'software & information industry association (siia)',
  'soclean, inc.',
  'sockdock, llc',
  'society for human resource management',
  'snugglycat inc - the ripple rug',
  'snap-on incorporated',
  'snakeemporium.com',
  'sms audio, llc',
  'smartsound software, inc.',
  'smarterfresh, llc',
  'sky deutschland fernsehen gmbh & co. kg',
  'skiboards superstore, inc.',
  'sinister mfg. co., inc. (sinister diesel)',
  'simpler trading, llc',
  'simon carey',
  'sigmacumlaude.com',
  'sigma beauty',
  'shop vac corporation',
  'shiseido company limited',
  'shewee ltd',
  'seisco international limited',
  'shimano, inc',
  'sheridan douglas press',
  'shabby chic',
  'sewing bee crinoline ladies embroidery patterns',
  'sew terific designs',
  'sensual candle',
  'sensation press',
  'seeing with sound - the voice',
  'secret-of-art',
  'searching for louis media',
  'scottcrew enterprises',
  'schlyer designs',
  'scantool.net, llc',
  'savanna group ltd - savanna samson',
  'sara moon',
  'susan lough',
  'sap',
  'sanyo electric co., ltd.',
  'santas christmas town',
  'saltworks, inc.',
  'salt life holdings, llc',
  'salt gems llc',
  'saleen',
  'sakura color products of america, inc.',
  'sadowsky guitars ltd.',
  'sado nation',
  'sacem',
  'rude awakening coffee house',
  'rro entertainment',
  'royal silk ltd',
  'royal british legion, the',
  'rowena cherry',
  'rothstein guitars',
  'roth company',
  'rosetta stone (uk) ltd',
  'rolls-royce',
  'rohde fine art',
  'fields',
  'rodan',
  'rocket science institute, inc.',
  'rn study spot',
  'rivington designs ltd',
  'right deals uk limited',
  'ridgerock tools',
  'rideworx pty ltd.',
  'richard avedon foundation',
  'rhodes international',
  'rgk innovations llc',
  'revitalash cosmetics',
  'revelation records',
  'reshoevn8r',
  'remote pro pty ltd',
  'reminderband inc.',
  'rembrandt charms',
  'relleciga official',
  'relix international, inc.',
  'red steagall\'s cowboy corner',
  'red monkey designs, inc.',
  'red hat society, inc.',
  'red camel racing ltd.',
  'red digital cinema camera company',
  'red bull gmbh',
  'rea.deeming beauty, inc. dba beautyblender',
  're/max international, inc.',
  'razormaid! productions',
  'rayverstar llc',
  'ray-ban',
  'rasasi perfumes',
  'rare sportsfilms inc.',
  'ranger doug\'s enterprises',
  'randomwalk, llc',
  'rainbow sandals, inc.',
  'radio flyer, inc.',
  'radiancy, inc.',
  'rachel caine',
  'quiksilver, inc',
  'quane cosmetics',
  'purdey',
  'provo craft & novelty, inc.',
  'pronto moda global limited',
  'profroster',
  'professorprofits.com',
  'procter & gamble',
  'probiotic america',
  'proactiv company sã¡rl',
  'princeton nutrients',
  'premiumfishing auctions store',
  'premier league',
  'pratico goods, llc',
  'prada s.a.',
  'practically darling designs',
  'powerportla, llc',
  'power straight',
  'power art design airbrushs pty ltd',
  'portage word-wide, inc. - manhattan portage',
  'popsockets llc',
  'poppy company',
  'pool cover corp. dba loop loc',
  'polymorphe, inc',
  'pneumatic components ltd',
  'plumeria bay, inc.',
  'ploom - pax labs',
  'plexus worldwide, inc',
  'plexaderm',
  'playtex products, llc',
  'playboy enterprises',
  'platypus wear, inc. dba bad boy brands',
  'platinum place',
  'plans designs',
  'piperwai, llc',
  'photomedex',
  'phiten gmbh',
  'philosophy, inc.',
  'pevonia international, llc',
  'peri k designs',
  'pen press publishing',
  'peak coffee ltd',
  'peachpopsclipartâ„¢',
  'pawsitively perfect bows',
  'patmont motor werks/go-pedâ®',
  'patchexpertsus',
  'patch me thru',
  'pasoday products ltd',
  'paradise film institute/big pictures',
  'panasonic corporation of north america',
  'pampered chef, the',
  'pamp sa',
  'pagedown technology, llc',
  'paddington and company limited',
  'packard club',
  'pacific market international, llc',
  'p rogers, inc.',
  'overstock.com inc.',
  'otterbox',
  'osnat',
  'osmosis skincare',
  'orthotebb health shoes, llc',
  'origami owl, llc',
  'orielle, llc',
  'organo gold',
  'orange usa',
  'opi products, inc',
  'open university',
  'onlinefabricstore',
  'one wise mac limited',
  'old & urban',
  'ã–ko-tex',
  'oki data corporation',
  'oakley, inc.',
  'nutramax laboratories, inc.',
  'nucific',
  'nu skin international inc.',
  'nsk americas, inc.',
  'nordstrom, inc.',
  'nomination s.r.l.',
  'noico',
  'niwot corporation dba specialty products company',
  'nissin foods holdings',
  'nintendo of america inc.',
  'nike',
  'nickolas muray photo archives, llc',
  'nichols photography',
  'new era cap company',
  'netpicks, llc',
  'nch software',
  'naturally plus',
  'national shooting sports foundation',
  'national products inc. dba ram mounts',
  'national historic mining initiative lc3',
  'national board of medical examiners - nbmeâ®',
  'national academy of television arts & sciences',
  'nandita arts',
  'n.v.e., inc.',
  'mywalit',
  'mystudygroup101',
  'mygift enterprise llc',
  'my poupette enterprises inc.',
  'my pageant kid',
  'mutbak',
  'multipure int\'l',
  'mud puppy mold company',
  'moviecraft inc.',
  'motion picture association of america (mpaa)',
  'mooneyes usa, inc.',
  'mocka products pty ltd',
  'mitchell repair information company',
  'miraflex s.a.',
  'ministry of defense',
  'ministero delle politiche agricole â€” icqrf',
  'miniclip sa',
  'minelab electronics',
  'mikimoto america',
  'mike barrett productions ltd.',
  'microsoft',
  'mga entertainment, inc. - a.b.c. international',
  'metropolitan kitchen',
  'merle norman cosmetics, inc.',
  'mercantile station 2',
  'melville direct, llc dba bits and pieces',
  'mellotron archives',
  'medieval moccasins',
  'medcosouth healthcare, llc',
  'mdesign',
  'mcgregor fashion group nv',
  'mccain photography',
  'mavala international',
  'matt groening',
  'master of illusions entertainment',
  'mary capan',
  'mars, inc.',
  'marianne\'s sol mate socks, inc.',
  'mannatech incorporated',
  'manchester united',
  'mamiya america corporation',
  'makaton charity',
  'magnolia rubberstamps',
  'magnetic poetry',
  'magnet shop',
  'mad dogg athletics, inc.',
  'luxe purses',
  'luxe jewels, llc dba stella & dot',
  'lori g ashley',
  'longchamp',
  'lomo industries ltd.',
  'live cell research',
  'lipsy ltd',
  'lip inkâ® international',
  'linkedin corporation',
  'linda mcsweeney',
  'light & dark productions',
  'lifted research group inc. (l-r-g)',
  'lifetrons switzerland gmbh',
  'lifeproof - treefrog',
  'lia sophia jewelery',
  'lexmark international inc.',
  'levi strauss & co.',
  'leupold & stevens, inc.',
  'letterrip decals',
  'lenny and eva, inc.',
  'lcr health',
  'laser design int\'l, llc',
  'las vegas wranglers professional hockey team',
  'larry hartsell seminars, inc.',
  'langley productions, inc.',
  'la chemise lacoste sa',
  'la boutique de bacchus',
  'kyser',
  'kun shoulder rest',
  'kronemann design studio pty. ltd. - house of kronemann usa',
  'knowledge in motion, inc.',
  'kleinn automotive accessories',
  'klasvsa (huixian dakang electronic commerce co., ltd.)',
  'kiniart studios',
  'king technology, inc.',
  'king baby studio',
  'kikka digga',
  'ketosource ltd.',
  'kettle foods ltd',
  'kerafiber europe limited',
  'kenvelo',
  'kenu, inc.',
  'kendama usa',
  'ke health llc, dba boricap',
  'kba enterprises llc - alban',
  'kate spade & company',
  'kason industries',
  'kando pictures limited',
  'kai z feng limited',
  'k.w. muth company, inc.',
  'k&m international, inc. - wild republic',
  'juvetress',
  'juul, inc.',
  'jty imports/exports pty ltd',
  'js&m sales & marketing inc.',
  'jrm licensing',
  'joy kroeger beckner, classical realism, from hounds to humans',
  'joseph rorie',
  'jordan design',
  'john deere',
  'jo condrill',
  'jnimports ltd. dba periea',
  'jmdl toys',
  'jim pace magic',
  'jeweltailor ltd.',
  'jet performance products, inc',
  'jenni leigh creations',
  'jemella ltd',
  'jedirect corp dba jetech design',
  'jayco (uk) limited',
  'james andrew grant',
  'jaguar & land rover',
  'jaclin dunne',
  'jackets4bikes',
  'it works marketing compliance',
  'irobot corporation',
  'iq implant devices',
  'invitamin, llc',
  'intuit, inc.',
  'international commercial television - ictv brands',
  'intenze',
  'insert knowledge here',
  'innovative textiles inc.',
  'innovative salon products, inc. (loma)',
  'innovative jk products llc',
  'inline tube, inc.',
  'infinite prosperity usa, llc - bluesky travel group pty ltd',
  'incipio technologies, inc.',
  'illume holding company llc',
  'ifixit',
  'ie works, llc',
  'hydor group',
  'hybrid systems ltd., inc. (hsl)',
  'hy cite corporation',
  'human touch, llc',
  'hugs not drugs',
  'huggalugs north america',
  'houselabels.com',
  'hotbuckles',
  'horizon hobby, inc.',
  'hook-eze pty ltd',
  'home power, inc.',
  'hoberman designs',
  'hks europe ltd',
  'hk wuppertal-solingen-remscheid',
  'himalaya drug company',
  'hillstock collection',
  'high island health, llc dba aneros',
  'hids4uâ®',
  'hewlett-packard company (hp ink & toner)',
  'herschel supply company ltd.',
  'hells angels motorcycle corporation italia',
  'heirs and estate of peter william ham',
  'hdmi licensing, llc',
  'hartley loudspeakers,inc.',
  'harley-davidson motor company',
  'hair flair ltd',
  'h&m',
  'guthy-renker corporation',
  'gunnar optiks, llc',
  'gundry md',
  'guess and marciano brands',
  'grimmspeed',
  'gretsch company',
  'graydog woodenware',
  'graphite design, inc.',
  'graphics technology hk limited',
  'grandma moses properties company',
  'grand lodge fraternal order of police',
  'grand chapter of phi sigma kappa, inc.',
  'gq electronics',
  'gottlieb development, llc',
  'gorilla tech ltd',
  'go nutrients',
  'gn netcom, dba jabra',
  'gmv productions',
  'glenns auto repair and performance llc dba glenns auto performance',
  'giraffe bath & body, llc',
  'gibson performance exhaust',
  'gibson brands, inc.',
  'giant uk ltd',
  'getonfleek',
  'gerber childrenswear, llc',
  'georgie girl australia',
  'georgia pacific corp.',
  'geneva laboratories ltd',
  'general motors',
  'gaylord entertainment company',
  'garry winogrand photography',
  'garmin (uk)',
  'garden selections ltd.',
  'games 4 hens ltd',
  'galiva inc.',
  'gaiam, inc.',
  'g. loomis, inc.',
  'funding usa llc',
  'fujikura composites',
  'frito-lay, inc.',
  'frantic stamper, inc.',
  'fretless finger guides',
  'fox (twentieth century fox film corporation)',
  'fossil, inc.',
  'fossil reproductions',
  'foshan shunde shines e-commerce co., ltd',
  'foscam intelligent technology co., ltd.',
  'fort worth stock show & rodeo',
  'formufit llc',
  'ford motor company',
  'footprints publishings inc.',
  'fluidity enterprises, inc.',
  'flowmaster',
  'flexibrace',
  'fleurville florida council of bromeliad societies, inc.',
  'fja mods',
  'fitness brands inc. / direct entertainment media group',
  'fishman',
  'first group / first great western',
  'fire house neon llc',
  'fire cam',
  'filemaker, inc.',
  'fgm ventures, llc dba petpost',
  'ferret company',
  'fender musical instruments corporation',
  'fã©dã©ration internationale de football association (fifa)',
  'federation against copyright theft (fact) ltd',
  'federal express corporation (fedex)',
  'fc bayern mã¼nchen',
  'fca us, llc',
  'fast eddie\'s vape shop and lounge, llc',
  'fashion polish',
  'farmland foods, inc.',
  'facelift ent. inc.',
  'fabriika',
  'fabjob.com',
  'fab1direct ltd - fablogix',
  'ezydog llc',
  'exel products',
  'eurotech photographics',
  'etrailer.com',
  'etienne aigner ag',
  'esa - entertainment software association',
  'erica skadsen/organic',
  'ergo baby carrier, inc.',
  'epson (uk) corporation',
  'epic coolers',
  'environ skin care pty ltd',
  'energybits inc.',
  'ember candles',
  'elope inc.',
  'electro-harmonix effects',
  'efi live limited co.',
  'edison nation',
  'edgar rice burroughs, inc.',
  'ecosphere associates, inc.',
  'eclipse records, inc.',
  'easton sports inc.',
  'east direct (uk) ltd',
  'eason media ltd',
  'eames office - lucia eames',
  'eagle creek enterprises - tim cox fine art',
  'e.i. du pont de nemours and company',
  'dynamic resource group',
  'duracell u.s. operations, inc.',
  'dunlop manufacturing, inc.',
  'dunhill',
  'duke of pearl, llc',
  'dtx international',
  'dsmb partners, llc dba activatedyou',
  'dropcrate, llc',
  'drive-in exchange, ltd',
  'dressthatman.com',
  'drageekiss ltd.',
  'dr. denese - skinscience labs, inc.',
  'dpcd',
  'doria international, inc.',
  'don\'t die, llc',
  'donmar enterprises, inc. - skyroofâ®',
  'dongguan hawson jewelry',
  'dollar shave club',
  'dolby laboratories inc. ("dolby")',
  'doggie bow ties',
  'doctor\'s associates inc. dba subway',
  'dms international',
  'dionne quintuplets, the',
  'dinnages (1989)',
  'digium, inc.',
  'diesel (london) ltd.',
  'dick harrell performance center, inc. (\'dhpc inc.\') licensing department',
  'dflk inc.',
  'dermalogica, inc.',
  'dermalmedix',
  'delta air lines, inc.',
  'delphi technologies',
  'dell computer corp.',
  'dedo weigert film gmbh',
  'db research l.l.p.',
  'davidson photography',
  'david barton',
  'dave\'s discount motors',
  'dave fant company of arkansas inc',
  'data-professionals',
  'dassault systemes s.a.',
  'dash america dba pearl izumi, inc.',
  'darkhorse ranch, inc.',
  'dark horse comics, inc.',
  'danworkshop.com',
  'dansko, llc',
  'daniel bingham design studio',
  'danes-r-us great dane & pet art',
  'dais enterprises',
  'cypress collectibles',
  'cynthia dakin',
  'cutecolors.com',
  'cutco cutlery corporation',
  'cucusoft, inc.',
  'crocs, inc.',
  'criswell embroidery & design',
  'creeks end crochet',
  'creature comforts ltd dba cornwall stoneware co.',
  'creative carvings by monte',
  'crazy aaron\'s puttyworld (crazy aaron\'s thinking putty)',
  'cranberry card company',
  'craft-e-creations',
  'cozy glow ltd.',
  'coway co., ltd',
  'country collectibles',
  'cosanti originals by paolo soleri',
  'coquetry clubwear',
  'cool mobility - johanson nominees pty.',
  'continental enterprises',
  'continental airlines',
  'competition clutch',
  'comitã© champagne',
  'comitã© georges mathieu',
  'colormetrics llc/ hairmarker llc',
  'colnago america, inc.',
  'collar and cuffs london',
  'coldwater creek inc.',
  'colart americas, inc.',
  'cocktailier llc',
  'coach, inc.',
  'cloud b, inc.',
  'cloche couture trademark',
  'cloanto it srl',
  'clayful creations',
  'classic-video',
  'chubby chico charms llc',
  'chocolate starfish ltd.',
  'chloã©',
  'chief architect, inc.',
  'chevron corporation',
  'chemsavers, inc.',
  'chaz dean studio',
  'charles cook',
  'chanel, inc.',
  'chalk & vermilion fine arts',
  'ceranet, inc.',
  'cbt nuggets, inc',
  'cbs entertainment and desilu, too, llc (unforgettable licensing)',
  'cartier',
  'carrs coins and rocks, inc.',
  'carmix-gps',
  'carmen\'s vintage collections',
  'carlstar group â€“ itp and carlisle brands',
  'carl mccoy (fields of the nephilim)',
  'car-freshner corporation',
  'care creations, inc.',
  'canyon dancer motorcycle products',
  'canyon chenille, inc.',
  'canon, inc.',
  'canadian standards association',
  'calutech, inc.',
  'bwthynbach',
  'business software alliance (eu)',
  'bushnell performance optics and tasco sales pty ltd.',
  'burlen fuel system limited',
  'burberry limited',
  'bumbleride inc.',
  'bug me video inc.',
  'buck knives, inc.',
  'bua, inc.',
  'bruce lee enterprises',
  'browning laboratories, inc.',
  'bronze gallery',
  'british phonographic industry limited',
  'brisant secure ltd',
  'bridgestone brands, llc',
  'brian smith',
  'brenda franklin',
  'boveda, inc.',
  'botanissa llc - see u baby',
  'bose corporation',
  'boppy company, the',
  'bonnie\'s plants',
  'bombardier recreational products, inc.',
  'blossomsugarart',
  'bloomberg l.p.',
  'blockware, llc dba great useful stuff',
  'blitzburgh sports',
  'blackpoint engineering, llc',
  'bittrex, inc.',
  'bissell homecare, inc.',
  'biotrust nutrition',
  'biotrade bulgaria ltd.',
  'bino products, llc',
  'billie w. taylor ii, ph.d.',
  'bill owen-cowboy artist',
  'bill lawrence products',
  'beverly hills md',
  'beyond cell',
  'benchmade knife company, inc.',
  'bell helicopter textron inc.',
  'bed band store',
  'beachbody, llc',
  'baume & mercier',
  'barstool sports, inc.',
  'barnett research and computer imaging',
  'bally pinball fun',
  'bad monkey productions',
  'b.h.p., inc. dba nialaya jewelry',
  'b. c. broncos',
  'b&m racing',
  'avedis zildjian, co.',
  'automotive technologies, inc.',
  'autoline industries',
  'auto meter products, inc. (autometer)',
  'autodata limited',
  'autism speaks, inc.',
  'authentic brands group llc',
  'australian made campaign limited',
  'australian gold, inc.',
  'austin city limits/klru',
  'auntie anne\'s, inc.',
  'atvimports',
  'atlantic research and marketing (a.r.m.s.)',
  'askorubeads',
  'ashleigh talbot',
  'arturia',
  'artbeats software, inc.',
  'ariix, llc',
  'arduino, llc',
  'ar15.com',
  'aqualibra uk',
  'apex tool group',
  'anvil forge art',
  'ansonia records, inc.',
  'annenberg media',
  'angela laframboise',
  'andy thomas',
  'andrew james worldwide',
  'analogman guitar effects',
  'amybug\'s attic',
  'amway corporation (us)',
  'amiclubwear.com',
  'americas drive-in corp. / sonic corp. & subsidiaries',
  'american welding society',
  'american weigh scales, inc.',
  'american eagle outfitters',
  'americana international ltd.',
  'amc photographics limited',
  'amari bliss',
  'aloe of america, inc. & forever living products int\'l.',
  'alm productions',
  'all saints (retail) ltd',
  'alientech srl',
  'alfresco heating',
  'alex perez',
  'aleratec, inc.',
  'alaska airlines',
  'aircraft technical publishers',
  'air force one air conditioning',
  'adt',
  'adobe',
  'action mining services inc.',
  'abercrombie & fitch',
  'aat - the association of acounting technicians',
  '3skulls paintball',
  '3m company',
  'pokemon',
  'vivosun',
  'waterpik',
  'aculief',
  'go girl',
  'gogirl',
  'kontrolfreek',
  'noco',
  'palksky',
  'sevicat',
  'bramble',
  'mochoi',
  'bakblade',
  'moolee',
  'yode',
  'elk',
  'danzix',
  'hismile',
  'mysmile',
  'roku',
  'shark',
  'wowwee',
  'styrofoam',
  'great stuff',
  'danisco',
  'sorona',
  'tyvek',
  'corian',
  'nomex',
  'kevlar',
  'veggetti pro',
  'veggetti power',
  'bestoffice',
  'veggetti',
  'turbo snake',
  'turbo scrub',
  'turbo pump',
  'turbo jet',
  'tiger wrench',
  'swivel sweeper',
  'strutz',
  'speed out',
  'simply straight',
  'relief wrap ultra',
  'posture doctor',
  'pink armor',
  'pillow pad',
  'piggy pop',
  'miracle socks',
  'miracle of aloe',
  'miracle bamboo pillow',
  'miracle bamboo cushion',
  'miracle bamboo bra',
  'mighty sight',
  'might sight',
  'micro mechanic',
  'magic tracks',
  'magic pad',
  'iron gym',
  'hurri clean',
  'huggle socks',
  'huggle pets',
  'huggle hoodie',
  'handy heater',
  'handy brite',
  'gopher',
  'furniture feet',
  'ever brite ultra',
  'dust daddy',
  'dryer balls',
  'breathe easy',
  'bowl light',
  'arctic air ultra',
  '5 second fix',
  'what do you meme',
  'olay',
  'secret',
  'scope',
  'oral-b',
  'crest',
  'clearblue',
  'pepto-bismol',
  'zzzquil',
  'align',
  'metamucil',
  'vicks',
  'gilette venus',
  'braun',
  'gillette',
  'cascade',
  'mr. clean',
  'febreze',
  'dawn',
  'swiffer',
  'hair food',
  'old spice',
  'herbal essences',
  'head & shoulders',
  'pantene',
  'always discreet',
  'tampax',
  'always',
  'charmin',
  'bounty',
  'gain',
  'ivory snow',
  'bounce',
  'downy',
  'tide',
  'pampers',
  'beachbody',
  'apple',
  'dorco',
  'eukanuba',
  'iams',
  'furminator',
  '8-in-1',
  'dingo',
  'nature’s miracle',
  'glofish',
  'marineland',
  'tetra',
  'black+decker',
  'russell hobbs',
  'george foreman',
  'pfister',
  'national hardware',
  'baldwin',
  'weiser',
  'kwikset',
  'remington',
  'ninja',
  'hamilton beach'
];

module.exports = {
  print,
  generateGuid,
  sleep,
  DEFAULT_COLLAGE_TEMPLATE,
  VERO_BRANDS
};
